### PR TITLE
Fix IsSimpleOp to support FindAllLocations for all geometry types

### LINKED ISSUE #753: IsSimpleOp does not support FindAllLocations for Polygon, MultiPoint and GeometryCollection
The following unit tests fail:
```java
  public void testPolygonAll() {
    checkIsSimpleAll("POLYGON ((0 0, 7 0, 6 -1, 6 -0.1, 6 0.1, 3 5.9, 3 6.1, 3.1 6, 2.9 6, 0 0))",
      BoundaryNodeRule.MOD2_BOUNDARY_RULE,
      "MULTIPOINT((6 0), (3 6))");
  }

  public void testMultiPointAll() {
    checkIsSimpleAll("MULTIPOINT((1 1), (1 2), (1 2), (1 3), (1 4), (1 4), (1 5), (1 5))",
      BoundaryNodeRule.MOD2_BOUNDARY_RULE,
      "MULTIPOINT((1 2), (1 4), (1 5))");
  }
  public void testGeometryCollectionAll() {
    checkIsSimpleAll("GEOMETRYCOLLECTION(MULTILINESTRING ((10 20, 90 20), (10 30, 90 30), (50 40, 50 10)), " +
      "MULTIPOINT((1 1), (1 2), (1 2), (1 3), (1 4), (1 4), (1 5), (1 5)))",
      BoundaryNodeRule.MOD2_BOUNDARY_RULE,
      "MULTIPOINT((50 20), (50 30), (1 2), (1 4), (1 5))");
  }
```

### PR DESCRIPTION
**Pull request by FObermaier**
... for 
* `Polygon`,
* `MultiPoint` and
* `GeometryCollection`

geometries.
fixes #753

Signed-off-by: Felix Obermaier <felix.obermaier@netcologne.de>

### CODE REVIEW

File: modules/core/src/main/java/org/locationtech/jts/operation/valid/IsSimpleOp.java [hunk 1]
```diff
@@ -203,54 +203,68 @@ private boolean computeSimple(Geometry geom)
   private boolean isSimpleMultiPoint(MultiPoint mp)
   {
     if (mp.isEmpty()) return true;
+    boolean res = true;
```
Comment (dr-jts) [inline modules/core/src/main/java/org/locationtech/jts/operation/valid/IsSimpleOp.java:206]: Better to call this `result` or `isSimple`

File: modules/core/src/main/java/org/locationtech/jts/operation/valid/IsSimpleOp.java [hunk 2]
```diff
@@ -275,19 +289,19 @@ private boolean isSimpleLinearGeometry(Geometry geom)
...
     LineIntersector li = new RobustLineIntersector();
-    private List<Coordinate> intersectionPts;
-    
-    private boolean hasInteriorInt;
-    private boolean hasInteriorVertexInt;
-    private boolean hasEqualSegments;
-    private boolean hasInteriorEndpointInt;
+    private final List<Coordinate> intersectionPts;
+
+    //private boolean hasInteriorInt;
```
Comment (dr-jts) [inline modules/core/src/main/java/org/locationtech/jts/operation/valid/IsSimpleOp.java:301]: Might as well delete these.

**Comment by dr-jts** [comment]
@FObermaier This is a nice enhancement - thanks!
