### PR TITLE
Fix SortedPackedIntervalRtree to be thread-safe

### LINKED ISSUE #747: PreparedPolygon is not thread safe
JavaDoc of PreparedGeometry says "Subclasses are intended to be thread-safe, to allow <code>PreparedGeometry</code>  to be used in a multi-threaded context  (which allows extracting maximum benefit from the prepared state)."
 However, PreparedPolygon is not thread safe, and under concurrent load may give sometimes incorrect result of #contains(Geometry) method. This affect and suggested fix are shown in this PR:  https://github.com/locationtech/jts/pull/746 .

### PR DESCRIPTION
**Pull request by ivanveselovsky-tomtom**
`SortedPackedIntervalRtree` is not thread-safe, because the `init` method is not synchronized.

This also contains some cleanup for `IndexedPointInAreaLocator`.

Fixes #747.

Signed-off-by: veselovs <ivan.veselovsky@tomtom.com>

### CODE REVIEW

**Comment by dr-jts** [comment]
Can you describe the core changes which allow concurrency?

File: modules/core/src/main/java/org/locationtech/jts/index/intervalrtree/SortedPackedIntervalRTree.java [hunk 1]
```diff
@@ -132,12 +127,7 @@ private void buildLevel(List src, List dest)
 			}
 		}
 	}
-	
-  private void printNode(IntervalRTreeNode node)
-  {
-    System.out.println(WKTWriter.toLineString(new Coordinate(node.min, level), new Coordinate(node.max, level)));
-  }
-
```
Comment (dr-jts) [inline modules/core/src/main/java/org/locationtech/jts/index/intervalrtree/SortedPackedIntervalRTree.java:140]: why is this removed?

File: modules/core/src/main/java/org/locationtech/jts/algorithm/locate/IndexedPointInAreaLocator.java [hunk 2]
```diff
@@ -102,15 +102,13 @@ public int locate(Coordinate p)
   private synchronized void createIndex() {
     if (index == null) {
       index = new IntervalIndexedGeometry(geom);
-      // no need to hold onto geom
-      geom = null;
```
Comment (dr-jts) [inline modules/core/src/main/java/org/locationtech/jts/algorithm/locate/IndexedPointInAreaLocator.java:106]: Is there a reason the geometry can't be freed?

File: modules/core/src/main/java/org/locationtech/jts/index/intervalrtree/SortedPackedIntervalRTree.java [hunk 3]
```diff
@@ -68,7 +66,7 @@ public void insert(double min, double max, Object item)
     leaves.add(new IntervalRTreeLeafNode(min, max, item));
 	}
 	
-  private void init()
+  private synchronized void init()
```
Comment (dr-jts) [inline modules/core/src/main/java/org/locationtech/jts/index/intervalrtree/SortedPackedIntervalRTree.java:69]: It looks like this is the key change for concurrency?

File: modules/core/src/main/java/org/locationtech/jts/algorithm/locate/IndexedPointInAreaLocator.java (hunk 2 above)
Comment (ivanveselovsky-tomtom) [reply modules/core/src/main/java/org/locationtech/jts/algorithm/locate/IndexedPointInAreaLocator.java:106]: The reason is that final ``` geom```  field looks clearer, and the performance effect of nulling it is likely negligible.
However, it can be safely nulled, fixed in this way.

File: modules/core/src/test/java/org/locationtech/jts/geom/prep/PreparedGeometryConcurrencyBugTest.java [hunk 4]
```diff
@@ -0,0 +1,67 @@
+package org.locationtech.jts.geom.prep;
```
Comment (dr-jts) [inline modules/core/src/test/java/org/locationtech/jts/geom/prep/PreparedGeometryConcurrencyBugTest.java:1]: This should go into the `test.jts.perf.geom.prep` package, because:
* it requires custom VM settings
* it is not guaranteed to reveal the issue on every run
* it may require significant execution time

File: modules/core/src/main/java/org/locationtech/jts/index/intervalrtree/SortedPackedIntervalRTree.java (hunk 1 above)
Comment (ivanveselovsky-tomtom) [reply modules/core/src/main/java/org/locationtech/jts/index/intervalrtree/SortedPackedIntervalRTree.java:140]: Because this is a dead code, method never invoked.

File: modules/core/src/main/java/org/locationtech/jts/index/intervalrtree/SortedPackedIntervalRTree.java (hunk 3 above)
Comment (ivanveselovsky-tomtom) [reply modules/core/src/main/java/org/locationtech/jts/index/intervalrtree/SortedPackedIntervalRTree.java:69]: yes.

File: modules/core/src/test/java/org/locationtech/jts/geom/prep/PreparedGeometryConcurrencyBugTest.java (hunk 4 above)
Comment (ivanveselovsky-tomtom) [reply modules/core/src/test/java/org/locationtech/jts/geom/prep/PreparedGeometryConcurrencyBugTest.java]: fixed.

**Comment by ivanveselovsky-tomtom** [comment]
> Can you describe the core changes which allow concurrency?

Critical change is synchronizing method  org.locationtech.jts.index.intervalrtree.SortedPackedIntervalRTree#init .
Before the fix absence of this synchronization was causing incorrect results under high concurrent load.

Other changes make the code more correct and reliable from the concurrency viewpoint, e.g "double-checked locking" in method org.locationtech.jts.algorithm.locate.IndexedPointInAreaLocator#createIndex can only work correctly if ``` index ``` field is volatile.

File: modules/core/src/main/java/org/locationtech/jts/index/intervalrtree/SortedPackedIntervalRTree.java (hunk 1 above)
Comment (dr-jts) [reply modules/core/src/main/java/org/locationtech/jts/index/intervalrtree/SortedPackedIntervalRTree.java:140]: Just comment it out then.  It may be used for debugging in the future.

Comment (ivanveselovsky-tomtom) [reply modules/core/src/main/java/org/locationtech/jts/index/intervalrtree/SortedPackedIntervalRTree.java:140]: fixed.
